build:
    info:
        file: classpath:build-info.yml
server:
  servlet:
    contextPath: /api
  port: 7777

swagger:
  api:
    title: sample-api
    contact.info: Team
    licence.url: #
    description:
    groupName: sample-api
    version: 1.0
    path:
      regex: /v.*/.*
  terms.of.service.url: #
  enabled: true

request:
  logging:
    enabled: true
    verbose: false

  
security:
  enable-csrf: false
  

spring:
  rabbitmq:
    uri: amqp://guest:guest@10.118.169.49:5672
    queue.name: "TSP.EmailNotification.Payload.Queue"
  data:
    mongodb:
      host: 10.118.169.49
      port: 27018
      database: notification
            
SendGrid_API_KEY: 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
              
    